name: CI
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Vale
      uses: errata-ai/vale-action@v1.0.4
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Link Checker
      id: lc
      uses: peter-evans/link-checker@v1
      with:
        args: -v -r *
